### ISSUE TITLE
"we don't have an account for that email address on this server"

### ISSUE THREAD

**Issue by natea** [pyvideo/richard#203]
It doesn't seem possible to register for a new account on the site. When I click on the Login link and login using my Mozilla Persona account, it says, "Either your login has failed or we don't have an account for that email address on this server."

I thought that it might just be a configuration issue with my http://localhost:8000 site, but then I tried to login to pyvideo.org and got the same message.

How do I associate my Mozilla Persona account with a new user on the Richard site?

**Comment by willkg** [comment]
We have #208 covering the "create a profile" page. Further, I changed things so people can create new accounts and log in now.

Given that, I'm going to close this out.
