### ISSUE TITLE
reduce complexity in title generation

### ISSUE THREAD

**Issue by willkg** [pyvideo/richard#273]
The page title generation is pretty complex. The view adds a variable to the context with the title, that gets pulled into the template being rendered which inherits from the base.html template which uses a pagetitle template tag to generate the title.

Because of this, it makes it hard to reason about what titles look like. Plus I think this makes L10N harder.

I think we should rethink how this works.

Maybe the best/easiest answer (for me at least) is to switch back to Jinja2 when we get to Django 1.8.

**Comment by codersquid** [comment]
Is #226 a duplicate of this?

**Comment by willkg** [comment]
It's not a strict duplicate, but it's the same topic. I'll copy/paste the description into a comment there and close this out.
